import { headers } from "next/headers";
import { getSetting } from "@/lib/turso";

export const dynamic = 'force-dynamic';

export async function generateMetadata() {
  const siteName = await getSetting("site_name") || "ShortenURL";
  const domainHost = headers().get('host') || 'domain.com';
  const plainDomain = domainHost.replace(/^https?:\/\//, '').replace(/^www\./, '');

  return {
    title: `Terms of Use - ${siteName}`,
    description: `Read the Terms of Use and Service Agreement for ${siteName}. These rules govern your acceptable use of our URL shortening platform.`,
    alternates: { canonical: '/terms' }
  };
}

export default async function TermsOfUsePage() {
  const siteName = await getSetting("site_name") || "ShortenURL";
  const headerList = headers();
  const host = headerList.get('host') || 'domain.com';
  const plainDomain = host.replace(/^https?:\/\//, '').replace(/^www\./, '');

  return (
    <div className="container">
      <div className="legal-wrapper">
        <div className="legal-header">
          <h1>Terms of Use</h1>
          <p className="legal-date">Last Updated: {new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}</p>
        </div>

        <div className="legal-content">
          <p>
            Welcome to <strong>{siteName}</strong>. These Terms of Use constitute a legally binding agreement made between you, whether personally or on behalf of an entity ("you") and {siteName} ("we," "us" or "our"), concerning your access to and use of the <strong>{plainDomain}</strong> website and its related URL shortening services.
          </p>
          <p>
            You agree that by accessing the website, you have read, understood, and agree to be bound by all of these Terms of Use. If you do not agree with all of these Terms of Use, then you are expressly prohibited from using the website and you must discontinue use immediately.
          </p>

          <h2>1. URL Shortening Services & Acceptable Use</h2>
          <p>
            {siteName} provides a platform that allows registered and unregistered users to transform long uniform resource locators (URLs) into shorter, manageable links. We provide this service to enhance the sharing experience across the internet. However, this service is provided with strict limitations. You agree to use our service solely for lawful purposes.
          </p>

          <h2>2. Strictly Prohibited Activities</h2>
          <p>To maintain the integrity of our platform and comply with international regulations and our advertising partners' policies, you are strictly prohibited from using our service to shorten links that redirect to or contain any of the following:</p>
          <ul>
            <li><strong>Malware and Phishing:</strong> Content designed to distribute viruses, trojans, worms, or trick users into revealing personal information (phishing).</li>
            <li><strong>Illegal Content:</strong> Child exploitation material, terrorism-related content, or instructions on how to perform illegal acts.</li>
            <li><strong>Copyright Infringement:</strong> Pirated software (cracks, keygens), illegal movie streaming, or unauthorized distribution of copyrighted material.</li>
            <li><strong>Spam and Botnets:</strong> Using automated scripts, botnets, proxies, or VPNs to artificially inflate click counts or bypass our advertising systems.</li>
            <li><strong>Extreme Violence & Hate Speech:</strong> Content that promotes violence, self-harm, or discrimination against any group.</li>
          </ul>
          <p>Violation of any of these rules will result in immediate account termination, deletion of all associated links, and forfeiture of any accumulated earnings without prior notice.</p>

          <h2>3. Monetization and Payouts</h2>
          <p>
            If you participate in our publisher monetization program, you agree that your traffic will be heavily monitored for fraudulent activities. Earnings are calculated based on valid, unique, human clicks. Clicks generated by bots, forced clicking methods, or deceptive practices will be rejected. {siteName} reserves the right to withhold payments if we suspect fraudulent traffic sources.
          </p>

          <h2>4. Account Responsibilities</h2>
          <p>
            You are entirely responsible for maintaining the confidentiality of your account login information and for all activities that occur under your account. You agree to notify us immediately of any unauthorized use or any other breach of security. We cannot and will not be liable for any loss or damage arising from your failure to comply with these security obligations.
          </p>

          <h2>5. Intellectual Property</h2>
          <p>
            The website, including its original content, features, and functionality, are owned by {siteName} and are protected by international copyright, trademark, patent, trade secret, and other intellectual property or proprietary rights laws.
          </p>

          <h2>6. Limitation of Liability</h2>
          <p>
            In no event shall {siteName}, nor its directors, employees, partners, agents, suppliers, or affiliates, be liable for any indirect, incidental, special, consequential or punitive damages, including without limitation, loss of profits, data, use, goodwill, or other intangible losses, resulting from your access to or use of or inability to access or use the Service.
          </p>

          <h2>7. Changes to Terms</h2>
          <p>
            We reserve the right, at our sole discretion, to modify or replace these Terms at any time. By continuing to access or use our Service after those revisions become effective, you agree to be bound by the revised terms.
          </p>
        </div>
      </div>
    </div>
  );
}
