import { headers } from "next/headers";
import { getSetting } from "@/lib/turso";

export const dynamic = 'force-dynamic';

export async function generateMetadata() {
  const siteName = await getSetting("site_name") || "ShortenURL";
  const domainHost = headers().get('host') || 'domain.com';
  const plainDomain = domainHost.replace(/^https?:\/\//, '').replace(/^www\./, '');

  return {
    title: `DMCA Notice & Takedown Policy - ${siteName}`,
    description: `Official DMCA Copyright Infringement Notice policy for ${siteName}. Understand how to report unauthorized distribution of copyrighted material.`,
    alternates: { canonical: '/dmca' }
  };
}

export default async function DMCAPage() {
  const siteName = await getSetting("site_name") || "ShortenURL";
  const headerList = headers();
  const host = headerList.get('host') || 'domain.com';
  const plainDomain = host.replace(/^https?:\/\//, '').replace(/^www\./, '');

  return (
    <div className="container">
      <div className="legal-wrapper">
        <div className="legal-header">
          <h1>DMCA Copyright Policy</h1>
          <p className="legal-date">Last Updated: {new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}</p>
        </div>

        <div className="legal-content">
          <p>
            <strong>{siteName}</strong> ("we", "us", or "our") respects the intellectual property rights of others and expects our users to do the same. In accordance with the Digital Millennium Copyright Act of 1998 ("DMCA"), we will respond expeditiously to claims of copyright infringement committed using the <strong>{plainDomain}</strong> service that are properly reported.
          </p>
          <p>
            <strong>Disclaimer:</strong> Please note that {siteName} is strictly a URL shortening utility. We do not host, store, or transmit the actual files, images, videos, or content that our shortened URLs redirect to. We only manage the redirection links. However, we are fully committed to disabling or removing any shortened URLs generated by our service that link to infringing materials upon receipt of a valid and complete DMCA takedown notice.
          </p>

          <h2>1. Filing a Notice of Infringement (Takedown Request)</h2>
          <p>
            If you are a copyright owner, or are authorized to act on behalf of one, please report alleged copyright infringements taking place on or through our platform by completing a DMCA Notice of Alleged Infringement. To be valid, your notice must include substantially the following information:
          </p>
          <ul>
            <li><strong>Physical or Electronic Signature:</strong> The signature of a person authorized to act on behalf of the owner of an exclusive right that is allegedly infringed.</li>
            <li><strong>Identification of the Work:</strong> Identification of the copyrighted work claimed to have been infringed, or, if multiple works are covered by a single notification, a representative list of such works.</li>
            <li><strong>Identification of the Link:</strong> The exact and specific {siteName} shortened URL (e.g., <em>{plainDomain}/AbCdE</em>) that you claim is redirecting to the infringing material. General domain references are not acceptable.</li>
            <li><strong>Contact Information:</strong> Information reasonably sufficient to permit us to contact you, such as an address, telephone number, and email address.</li>
            <li><strong>Good Faith Statement:</strong> A statement that you have a good faith belief that use of the material in the manner complained of is not authorized by the copyright owner, its agent, or the law.</li>
            <li><strong>Accuracy Statement:</strong> A statement that the information in the notification is accurate, and under penalty of perjury, that you are authorized to act on behalf of the owner of an exclusive right that is allegedly infringed.</li>
          </ul>
          <p>Failure to include all of the above information may result in a delay of the processing of your complaint.</p>

          <h2>2. Counter-Notification Procedures</h2>
          <p>
            If a user believes that their shortened URL was removed or disabled by mistake or misidentification, they may file a counter-notice. To be effective, a Counter-Notice must be a written communication that includes:
          </p>
          <ul>
            <li>The user's physical or electronic signature.</li>
            <li>Identification of the URL that has been removed or to which access has been disabled.</li>
            <li>A statement under penalty of perjury that the user has a good faith belief that the material was removed or disabled as a result of mistake or misidentification.</li>
            <li>The user's name, address, and telephone number, and consent to local federal court jurisdiction.</li>
          </ul>

          <h2>3. Repeat Infringer Policy</h2>
          <p>
            In accordance with the DMCA, {siteName} has adopted a policy of terminating, in appropriate circumstances and at our sole discretion, users who are deemed to be repeat infringers. We proactively monitor accounts that frequently generate links subject to valid DMCA takedowns.
          </p>

          <h2>4. Submission of Notices</h2>
          <p>
            Please submit all DMCA Notices to our official abuse email address listed on our contact page. We strive to process all valid requests within 24 to 48 hours of receipt.
          </p>
        </div>
      </div>
    </div>
  );
}
