import { headers } from "next/headers";
import { getSetting } from "@/lib/turso";

export const dynamic = 'force-dynamic';

// 1. GENERATE META TITLE & DESCRIPTION
export async function generateMetadata() {
  const siteName = await getSetting("site_name") || "ShortenURL";
  const domainHost = headers().get('host') || 'domain.com';
  const plainDomain = domainHost.replace(/^https?:\/\//, '').replace(/^www\./, '');

  return {
    title: `DMCA Copyright Policy - ${siteName}`,
    description: `DMCA Notice and Takedown Policy for ${siteName} (${plainDomain}). Learn how to report copyright infringement and intellectual property violations.`,
    alternates: {
      canonical: '/dmca',
    }
  };
}

export default async function DMCAPage() {
  // 2. AMBIL DATA NAMA SITUS DAN DOMAIN
  const siteName = await getSetting("site_name") || "ShortenURL";
  const headerList = headers();
  const host = headerList.get('host') || 'domain.com';
  const plainDomain = host.replace(/^https?:\/\//, '').replace(/^www\./, '');

  return (
    <div className="container" style={{ marginTop: '50px', marginBottom: '80px', maxWidth: '900px' }}>
      
      {/* HEADER HALAMAN */}
      <div style={{ marginBottom: '40px', borderBottom: '2px solid #eee', paddingBottom: '20px' }}>
        <h1 style={{ fontWeight: '800', color: '#2c3e50', fontSize: '36px' }}>DMCA Copyright Policy</h1>
        <p className="text-muted" style={{ fontSize: '15px' }}>Last Updated: {new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}</p>
      </div>

      {/* KONTEN TEKS RAPIH (TANPA BOX) */}
      <div style={{ 
        fontSize: '16px', 
        lineHeight: '1.8', 
        color: '#444',
        textAlign: 'justify'
      }}>
        <p>
          <strong>{siteName}</strong> ("we", "us", or "our") respects the intellectual property rights of others and expects our users to do the same. In accordance with the Digital Millennium Copyright Act of 1998, the text of which may be found on the U.S. Copyright Office website at <a href="http://www.copyright.gov/legislation/dmca.pdf" target="_blank" rel="noopener noreferrer">http://www.copyright.gov/legislation/dmca.pdf</a>, we will respond expeditiously to claims of copyright infringement committed using the <strong>{plainDomain}</strong> service that are reported to our Designated Copyright Agent.
        </p>
        <p>
          Please note that {siteName} is a URL shortening service. We do not host the files, images, or content that our shortened URLs redirect to. However, we are committed to disabling or removing any shortened URLs generated by our service that link to infringing materials upon receipt of a valid DMCA notice.
        </p>

        <h2 style={{ fontSize: '24px', fontWeight: '700', color: '#2c3e50', marginTop: '40px', marginBottom: '15px' }}>1. Notice of Infringement (Takedown Request)</h2>
        <p>
          If you are a copyright owner, or are authorized to act on behalf of one, or authorized to act under any exclusive right under copyright, please report alleged copyright infringements taking place on or through the Site by completing the following DMCA Notice of Alleged Infringement and delivering it to our Designated Copyright Agent.
        </p>
        <p>Upon receipt of the Notice as described below, we will take whatever action, in our sole discretion, we deem appropriate, including the immediate removal of the challenged shortened URL from the Site.</p>
        <p>To file a DMCA Notice of Alleged Infringement, you must provide a written communication that includes the following items:</p>
        <ul style={{ paddingLeft: '20px', marginBottom: '20px' }}>
          <li><strong>Identify the copyrighted work:</strong> Provide a description of the copyrighted work that you claim has been infringed. If multiple copyrighted works are covered by this Notice, you may provide a representative list of the copyrighted works that you claim have been infringed.</li>
          <li><strong>Identify the material or link:</strong> Provide the specific {siteName} shortened URL (e.g., {plainDomain}/xyz123) that you claim is infringing or that points to infringing activity. General site URLs are not sufficient.</li>
          <li><strong>Contact Information:</strong> Provide your mailing address, telephone number, and, if available, email address.</li>
          <li><strong>Good Faith Statement:</strong> Include the following statement: <em>"I hereby state that I have a good faith belief that the disputed use of the copyrighted material or reference or link to such material is not authorized by the copyright owner, its agent, or the law."</em></li>
          <li><strong>Perjury Statement:</strong> Include the following statement: <em>"I hereby state that the information in this Notice is accurate and, under penalty of perjury, that I am the owner, or authorized to act on behalf of the owner, of the copyright or of an exclusive right under the copyright that is allegedly infringed."</em></li>
          <li><strong>Signature:</strong> Provide your full legal name and your electronic or physical signature.</li>
        </ul>

        <h2 style={{ fontSize: '24px', fontWeight: '700', color: '#2c3e50', marginTop: '40px', marginBottom: '15px' }}>2. Counter-Notification Procedures</h2>
        <p>
          If you believe that a shortened URL you created was removed or disabled by mistake or misidentification, you may file a counter-notice with our Designated Copyright Agent. To be effective, a Counter-Notice must be a written communication that includes the following:
        </p>
        <ul style={{ paddingLeft: '20px', marginBottom: '20px' }}>
          <li>Your physical or electronic signature.</li>
          <li>Identification of the material (the shortened URL) that has been removed or to which access has been disabled and the location at which the material appeared before it was removed or access to it was disabled.</li>
          <li>A statement under penalty of perjury that you have a good faith belief that the material was removed or disabled as a result of mistake or misidentification of the material to be removed or disabled.</li>
          <li>Your name, address, and telephone number, and a statement that you consent to the jurisdiction of the Federal District Court for the judicial district in which the address is located, and that you will accept service of process from the person who provided the original notification of infringement or an agent of such person.</li>
        </ul>
        <p>
          Upon receipt of a valid counter-notice, we will promptly forward a copy to the person who provided the original DMCA notice. If the original complainant does not notify us within 10-14 business days that they have filed an action seeking a court order to restrain the subscriber from engaging in infringing activity, we may restore the disabled link.
        </p>

        <h2 style={{ fontSize: '24px', fontWeight: '700', color: '#2c3e50', marginTop: '40px', marginBottom: '15px' }}>3. Repeat Infringer Policy</h2>
        <p>
          In accordance with the DMCA and other applicable law, {siteName} has adopted a policy of terminating, in appropriate circumstances and at our sole discretion, users who are deemed to be repeat infringers. We may also at our sole discretion limit access to the Site and/or terminate the accounts of any users who infringe any intellectual property rights of others, whether or not there is any repeat infringement.
        </p>

        <h2 style={{ fontSize: '24px', fontWeight: '700', color: '#2c3e50', marginTop: '40px', marginBottom: '15px' }}>4. Submitting Your Notice</h2>
        <p>
          Please submit all DMCA Notices and Counter-Notices through our official contact page or directly to the email address provided in our administrative dashboard. Do not send non-DMCA inquiries to the copyright agent, as they will be ignored.
        </p>

        <div style={{ marginTop: '50px', padding: '20px', backgroundColor: '#fcf8e3', borderLeft: '5px solid #faebcc', borderRadius: '4px' }}>
          <strong>Important Warning:</strong> Under Section 512(f) of the DMCA, any person who knowingly materially misrepresents that material or activity is infringing may be subject to liability for damages, including costs and attorneys' fees.
        </div>

      </div>
    </div>
  );
}
